# Generated by Django 4.2 on 2023-06-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_active",
            field=models.BooleanField(default=False),
        ),
    ]
