# Generated by Django 4.2 on 2023-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_chat_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="voice_active",
            field=models.BooleanField(default=False),
        ),
    ]
