# Generated by Django 4.2 on 2023-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_voice_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enter_voicechat",
            field=models.DateTimeField(null=True),
        ),
    ]
