# Generated by Django 4.2 on 2023-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_enter_voicechat"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enter_chat",
            field=models.DateTimeField(null=True),
        ),
    ]
