# Generated by Django 4.2 on 2023-06-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_contact",
                to="chat.contact",
            ),
        ),
    ]
