# Generated by Django 4.2 on 2023-06-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chat_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.message",
            ),
        ),
    ]
