# Generated by Django 4.2 on 2023-06-26 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_alter_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
