# Generated by Django 4.2 on 2023-06-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_message_room_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("consult_text", models.TextField()),
                ("consult_date", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(null=True)),
                ("title", models.TextField()),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_counselor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
