# Generated by Django 4.2 on 2023-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
