# Generated by Django 4.2 on 2023-06-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voicechat", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_contact",
                to="voicechat.contact",
            ),
        ),
    ]
